version: '3.7'

networks:
  sdl_net:
   name: sdl_net

services:
  #######################
  # SDL Visual Explorer #
  #######################
  visual-explorer:
    container_name: sdl_visual-explorer
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./visual-explorer/app:/usr/src/app
    working_dir: /usr/src/app
    command: ["sh", "-c", "npm install && npm run-script start"]
    depends_on:
      - visual-analytics-engine
    networks:
      - sdl_net

  ###############################
  # SDL Visual Analytics Engine #
  ###############################
  visual-analytics-engine:
    container_name: sdl_visual-analytics-engine
    image: sdl_visual-analytics-engine:latest
    build:
      context: ./visual-analytics-engine/
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./visual-analytics-engine/app:/usr/src/app
      - ./visual-analytics-engine/data/input:/data/input
      - data:/data/output
    env_file: ./test-db/postgres.env
    working_dir: /usr/src/app
    command: ["python", "app.py", "--port", "8080", "--dev"]
    networks:
      - sdl_net

  ###############
  # JUPYTER LAB #
  ###############
  jupyter-lab:
    container_name: sdl_jupyter
    image: sdl_jupyter:latest
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    ports:
      - 8889:8888
    working_dir: /home/jovyan
    command: ["sh", "-c", "cd /home/jovyan/notebooks && jupyter-lab"]
    networks:
      - sdl_net

  ###########
  # V-Plots #
  ###########
  v-plots:
    container_name: sdl_v-plots
    image: node:latest
    ports:
      - "9000:9000"
    volumes:
      - ./v-plots/app:/usr/src/app
    working_dir: /usr/src/app
    command: ["sh", "-c", "npm install && npx bower --allow-root install && npx grunt serve"]
    networks:
      - sdl_net
  
  ####################
  # Postgres Test DB #
  ####################
  test-db:
    container_name: sdl_test-db
    image: postgres:latest
    volumes:
      - ./test-db/initscripts/:/docker-entrypoint-initdb.d/
      - ./test-db/data/:/data/
    env_file: ./test-db/postgres.env
    ports:
      - "5432:5432"
    networks:
      - sdl_net


volumes:
  data:
    external: false
